- .github/issue-form.yml
- 리뷰어가 중점적으로 봐야하는 부분을 바로 알 수 있도록 변경된 내용을 나열합니다.
- 고민했던 포인트가 없다면 **삭제**해도 됩니다.
- **어떤 고민**을 해서 **어떤 결과**가 나왔는지 작성해주세요.
- 경험 공유나 다른 팀원들의 생각을 들을 수 있을 것 같아요.
- 도움이 필요한 부분이 없다면 **삭제** 해도 됩니다.
- **팀원들의 의견이 꼭 필요한 부분**을 작성해주세요.
- **팀원들은 놓치지 않고 꼭 이 항목을 보고 의견을 주세요.**
> FS-2: 지라와 깃허브 연동 시도

- .github/workflows/create-jira-issue.yml
- src/main/java/com/factseekerbackend/fsController.java
- 리뷰어가 중점적으로 봐야하는 부분을 바로 알 수 있도록 변경된 내용을 나열합니다.
- 고민했던 포인트가 없다면 **삭제**해도 됩니다.
- **어떤 고민**을 해서 **어떤 결과**가 나왔는지 작성해주세요.
- 경험 공유나 다른 팀원들의 생각을 들을 수 있을 것 같아요.
- 도움이 필요한 부분이 없다면 **삭제** 해도 됩니다.
- **팀원들의 의견이 꼭 필요한 부분**을 작성해주세요.
- **팀원들은 놓치지 않고 꼭 이 항목을 보고 의견을 주세요.**
> Fs 2 예시 지라와 깃허브 연동

- build.gradle
- src/main/java/com/factseekerbackend/config/SecurityConfig.java
- src/main/java/com/factseekerbackend/controller/UserController.java
- src/main/java/com/factseekerbackend/dto/UserRegisterRequest.java
- src/main/java/com/factseekerbackend/entity/User.java
- src/main/java/com/factseekerbackend/repository/UserRepository.java
- src/main/java/com/factseekerbackend/service/UserService.java
- src/main/resources/application.yml
> feat(user): 회원가입 기능 구현

- .github/workflows/deploy.yml
- src/main/java/com/factseekerbackend/domain/user/controller/UserController.java
- src/main/java/com/factseekerbackend/domain/user/repository/UserRepository.java
- src/main/java/com/factseekerbackend/domain/user/service/UserService.java
- src/main/java/com/factseekerbackend/global/auth/jwt/JwtTokenProvider.java
- src/main/java/com/factseekerbackend/global/auth/jwt/service/JwtService.java
> [Fs-19] feat/withdraw user

- .github/workflows/apify-trigger.yml
- apify 작업 시간 2시간으로 수정완료.
- 
-
> feat: apify와 Github Actions 연동 수정

- src/main/java/com/factseekerbackend/global/politicalTranding/TrendScheduler.java
- src/main/java/com/factseekerbackend/global/politicalTranding/controller/MockTrendController.java
- src/main/java/com/factseekerbackend/global/politicalTranding/controller/TrendController.java
- src/main/java/com/factseekerbackend/global/politicalTranding/dto/TrendApiResponse.java
- src/main/java/com/factseekerbackend/global/politicalTranding/service/TrendService.java
- src/main/resources/application.yml
Reverts Hanium-FactSeeker/factseeker-backend#52
잘못된 브랜치 설정으로 pr 취소합니다.
> Revert "fix: 서버 url 변경했습니다"

- src/main/java/com/factseekerbackend/domain/analysis/controller/VideoAnalysisController.java
- src/main/java/com/factseekerbackend/domain/analysis/controller/dto/response/KeywordsResponse.java
- src/main/java/com/factseekerbackend/domain/analysis/service/VideoAnalysisService.java
- src/main/java/com/factseekerbackend/domain/youtube/controller/YoutubeController.java
- src/main/java/com/factseekerbackend/domain/youtube/controller/dto/response/YoutubeSearchResponse.java
- src/main/java/com/factseekerbackend/domain/youtube/service/YoutubeSearchService.java
- src/main/java/com/factseekerbackend/domain/youtube/service/YoutubeService.java
- src/main/java/com/factseekerbackend/global/auth/jwt/service/JwtService.java
- src/main/java/com/factseekerbackend/global/config/SecurityConfig.java
- 이슈에 등록된 내용들 완료했습니다. [FS-36](https://factseeker.atlassian.net/browse/FS-36)
- 유튜브 정보를 어떻게 프론트에 전달할지 고민했는데 그 결과 리스트로 한번에 반환하는 방법으로 결정했습니다~
[FS-36]: https://factseeker.atlassian.net/browse/FS-36?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fs 36 feature/youtube parsing

- src/main/java/com/factseekerbackend/domain/analysis/config/RestClientConfig.java
- src/main/java/com/factseekerbackend/global/auth/jwt/filter/JwtAuthenticationFilter.java
- src/main/java/com/factseekerbackend/global/config/SecurityConfig.java
- src/main/java/com/factseekerbackend/infrastructure/naver/controller/NewsSearchController.java
- src/main/java/com/factseekerbackend/infrastructure/naver/newsapi/NaverClient.java
- src/main/java/com/factseekerbackend/infrastructure/naver/newsapi/dto/request/NewsRequest.java
- src/main/java/com/factseekerbackend/infrastructure/naver/newsapi/dto/response/NewsItem.java
- src/main/java/com/factseekerbackend/infrastructure/naver/newsapi/dto/response/NewsResponse.java
- src/main/resources/application-local.yml
- RestClient 활용해 외부 api 연결했습니다.
- 뉴스 데이텨 기본 10개 가져오는것 완료했습니다.
- 스웨거로 예시 넣었습니다.
- RestClient를 어떻게 써야하는지 잘 몰랐는데, 빈 이름으로 구별하면 되어서 그렇게 했습니당
> [FS-37] 뉴스 데이터 연결완료.

- .gitignore
- src/main/java/com/factseekerbackend/domain/analysis/controller/VideoAnalysisController.java
- src/main/java/com/factseekerbackend/domain/analysis/controller/dto/request/VideoIdsRequest.java
- src/main/java/com/factseekerbackend/domain/analysis/controller/dto/request/VideoUrlRequest.java
- src/main/java/com/factseekerbackend/domain/analysis/controller/dto/response/AnalysisPercentResponse.java
- src/main/java/com/factseekerbackend/domain/analysis/controller/dto/response/AnalysisStartResponse.java
- src/main/java/com/factseekerbackend/domain/analysis/controller/dto/response/KeywordsResponse.java
- src/main/java/com/factseekerbackend/domain/analysis/controller/dto/response/PercentStatusData.java
- src/main/java/com/factseekerbackend/domain/analysis/controller/dto/response/PercentStatusResponse.java
- src/main/java/com/factseekerbackend/domain/analysis/controller/dto/response/Top10AnalysisPercentResponse.java
- src/main/java/com/factseekerbackend/domain/analysis/controller/dto/response/VideoAnalysisResponse.java
- src/main/java/com/factseekerbackend/domain/analysis/controller/dto/response/fastapi/ClaimDto.java
- src/main/java/com/factseekerbackend/domain/analysis/controller/dto/response/fastapi/EvidenceDto.java
- src/main/java/com/factseekerbackend/domain/analysis/controller/dto/response/fastapi/FastApiFactCheckResponse.java
- src/main/java/com/factseekerbackend/domain/analysis/entity/Top10VideoAnalysis.java
- src/main/java/com/factseekerbackend/domain/analysis/entity/VideoAnalysisStatus.java
- src/main/java/com/factseekerbackend/domain/analysis/repository/Top10VideoAnalysisRepository.java
- src/main/java/com/factseekerbackend/domain/analysis/service/VideoAnalysisService.java
- src/main/java/com/factseekerbackend/domain/analysis/service/fastapi/FactCheckResultService.java
- src/main/java/com/factseekerbackend/domain/analysis/service/fastapi/FactCheckTriggerService.java
- src/main/java/com/factseekerbackend/global/auth/jwt/filter/JwtAuthenticationFilter.java
- src/main/java/com/factseekerbackend/global/exception/ErrorCode.java
- src/main/java/com/factseekerbackend/global/exception/GlobalExceptionHandler.java
- src/main/java/com/factseekerbackend/global/exception/InvalidTokenException.java
- src/main/resources/application.yml
- 리스트로 요청 올 경우 분석중인 유튜브 들이 있기 때문에, Pending 과 같은 상태 추가했습니다.
- 유튜브 링크 검증로직 추가해서 상태코드 리턴하도록 수정했습니다.
- 리스트로 할 경우 하나의 요청이라도 실패하면 에러로 처리되어서 이걸 상태 컬럼을 활용해 해결했습니다.
> [FS-39] 유튜브 퍼센트 dto 구성 완료.

- src/main/java/com/factseekerbackend/domain/analysis/service/fastapi/FactCheckTriggerService.java
- src/main/java/com/factseekerbackend/domain/politician/service/PoliticianTrustAnalysisService.java
- src/main/java/com/factseekerbackend/global/config/AsyncConfig.java
현재 async의 별도 설정이 없어 async를 사용해도 다른 api의 사용이 막히는 문제를 수정했습니다.
> [Fix] aync 사용 시 동일한 풀을 사용하지 않도록 수정

- src/main/java/com/factseekerbackend/domain/politician/service/PoliticianTrustAnalysisService.java
인물 분석 로직을 transaction 밖으로 빼내어 db lock 문제를 수정했습니다.
> [Fix] transaction문제로 인한 db lock 문제 수정

- src/main/java/com/factseekerbackend/domain/analysis/controller/VideoAnalysisController.java
- src/main/java/com/factseekerbackend/domain/analysis/controller/dto/response/KeywordsResponse.java
- src/main/java/com/factseekerbackend/domain/analysis/service/VideoAnalysisService.java
- src/main/java/com/factseekerbackend/global/exception/ErrorCode.java
> [FS-40] refactor: 에러 코드 반환 변경

- src/main/java/com/factseekerbackend/domain/analysis/service/fastapi/FastApiBridgeService.java
> hotfix: 스케쥴러 활성화

- src/main/java/com/factseekerbackend/domain/youtube/service/PopularCacheRefresher.java
> [FS-40] 스케쥴러 수정.

- src/main/java/com/factseekerbackend/domain/analysis/controller/VideoAnalysisController.java
- 배포시 502 에러 수정하기 위해 에러 수정했습니다.
> [FS-40] 스웨거 및 엔드포인트 수정했습니다.

- src/main/java/com/factseekerbackend/domain/analysis/controller/VideoAnalysisController.java
Reverts Hanium-FactSeeker/factseeker-backend#108
> Revert "Revert "Revert "[Merge] 개발 환경에서 배포 환경으로의 merge"""

- src/main/java/com/factseekerbackend/domain/youtube/config/YoutubeConfig.java
- src/main/java/com/factseekerbackend/domain/youtube/controller/dto/response/VideoDto.java
- src/main/java/com/factseekerbackend/domain/youtube/controller/dto/response/YoutubeSearchResponse.java
- src/main/java/com/factseekerbackend/domain/youtube/service/PopularCacheRefresher.java
- src/main/java/com/factseekerbackend/global/util/TextSanitizer.java
- 유튜브  제목 전처리 기능과 redis 호출 실패시 재호출 하는 기능 추가했습니다.
> feat: 유튜브 제목 전처리 기능 구현

- .github/workflows/apify-trigger.yml
- src/main/java/com/factseekerbackend/domain/apify/controller/ApifyController.java
- src/main/java/com/factseekerbackend/domain/apify/dto/request/ApifyRequest.java
- src/main/java/com/factseekerbackend/domain/apify/entity/PoliticianSnsPost.java
- src/main/java/com/factseekerbackend/domain/apify/repository/PoliticianSnsPostRepository.java
- src/main/java/com/factseekerbackend/domain/apify/service/ApifyService.java
- src/main/java/com/factseekerbackend/domain/politician/repository/PoliticianRepository.java
- apify 데이터 json형태로 수령 및 해당 데이터 디비 저장 로직 구현.
- 
-
> feat: apify 데이터, 디비 저장 로직 구현

- src/main/java/com/factseekerbackend/global/config/SecurityConfig.java
기존에 등록해뒀던 URL에 www를 추가했습니다. 혹시 몰라 버셀 서버도 추가했습니다.
> [Fix] 프론트 배포서버 cors 수정

- src/main/java/com/factseekerbackend/domain/analysis/controller/VideoAnalysisController.java
- src/main/java/com/factseekerbackend/domain/analysis/service/fastapi/FactCheckTriggerService.java
Reverts Hanium-FactSeeker/factseeker-backend#132
> Revert "Revert "Merge: 메인 merge""
